version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: game
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - no_egress

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://game:gamepass@db:5432/game
      - FLAG_SALT=replace_with_a_secret_salt
      - INITIAL_ADMIN=bo:testpass    # optional bootstrap user
    ports:
      - "8000:8000"
    networks:
      - frontend
      - no_egress

  level1:
    build: ./challenges/level1
    networks:
      - no_egress
    restart: always

  level2:
    build: ./challenges/level2
    networks:
      - no_egress
    restart: always
   
  level3:
    build: ./challenges/level3
    networks:
      - no_egress
    restart: always

  level4:
    build: ./challenges/level4
    networks:
      - no_egress
    restart: always
  
  level5:
    build: ./challenges/level5
    networks:
      - no_egress
    restart: always
  
  jump:
    build: ./challenges/jump
    depends_on:
      - backend
      - level1
      - level2
      - level3 
      - level4
      - level5
    ports:
      - "3333:22"
    networks:
      - frontend
      - no_egress
    restart: always

networks:
  no_egress:
    driver: bridge
    internal: true
  frontend:
    driver: bridge

volumes:
  dbdata:
